steps:
   - id: Test out gcloud commands
     name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: 'gcloud'
     env:
     - "_DIGEST_CONTAINER_PATH=us-central1-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPO_NAME/cd"
     - '_REVISION_ID=$(gcloud container images list-tags $_DIGEST_CONTAINER_PATH --format='value(tags)' --limit=1)'
     - '_CONTAINER_PATH=$LOCATION-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPO_NAME/cd:$REVISION_ID'
     - '_DIGEST=$(gcloud container images describe ${_CONTAINER_PATH} --format='get(image_summary.digest)')'
     - '_CONTAINER_IMAGE_DIGEST_PATH=${_DIGEST_CONTAINER_PATH}@${_DIGEST}'
     args: ['deploy', 'releases', 'create', 'r-$REVISION_ID', '--project=$PROJECT_ID','--region=us-central1','--delivery-pipeline=ci-cd-test', '--images=notes-app-image=us-central1-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPO_NAME/cd@$_CONTAINER_IMAGE_DIGEST_PATH']
images: ['us-central1-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPO_NAME/cd@$_CONTAINER_IMAGE_DIGEST_PATH']
