steps:
   - id: Create a cloud deploy release and this will also deploy the release to the first target ie test
     name: 'gcr.io/cloud-builders/gcloud'
     env:
     - '_CONTAINER_REPO_NAME=test-repo'
     - '_DIGEST_CONTAINER_PATH=us-central1-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPO_NAME/cd'
     - "_REVISION_ID=$(gcloud container images list-tags $_DIGEST_CONTAINER_PATH --format='value(tags)' --limit=1)"
     - "_CONTAINER_PATH=$LOCATION-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPO_NAME/cd:$REVISION_ID"
     - "_DIGEST=$(gcloud container images describe ${_CONTAINER_PATH} --format='get(image_summary.digest)')"
     - "_CONTAINER_IMAGE_DIGEST_PATH=${_DIGEST_CONTAINER_PATH}@${_DIGEST}"
     args: 
     - echo $(_CONTAINER_IMAGE_DIGEST_PATH) | md5sum | awk '{print $1}'
#images: ['us-central1-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPO_NAME/cd@$_CONTAINER_IMAGE_DIGEST_PATH']
