steps:
   - id: Create a cloud deploy release and this will also deploy the release to the first target ie dev
     name: 'gcr.io/cloud-builders/gcloud'
     args: ['deploy', 'releases', 'create', 'r-$COMMIT_SHA', '--project=$PROJECT_ID','--region=us-central1','--delivery-pipeline=ci-cd-test', '--images=notes-app-image=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME@$COMMIT_SHA']
images: ['us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME@$COMMIT_SHA']
